# Generated by Django 3.2.6 on 2021-10-08 07:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_assignment_assignmentsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 7, 33, 11, 809921, tzinfo=utc)),
        ),
    ]
