# Generated by Django 3.2.6 on 2021-10-08 07:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_assignment_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 7, 55, 32, 819866, tzinfo=utc)),
        ),
    ]
