# Generated by Django 3.2.6 on 2021-10-08 07:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_auto_20211008_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 7, 56, 46, 682477, tzinfo=utc)),
        ),
    ]
