# Generated by Django 3.2.6 on 2021-10-08 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_alter_assignment_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='created_by',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 9, 20, 38, 309778, tzinfo=utc)),
        ),
    ]
