# Generated by Django 3.2.6 on 2021-10-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_auto_20211008_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='user',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='AssignmentSubmission',
        ),
    ]
